use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

use pretty::{termcolor, Pretty};
use rustc_hir::{
    def_id::{DefId, LocalDefId},
    HirId,
};
use rustc_index::IndexVec;
use rustc_middle::ty::{self as mir_ty, TyCtxt};

use crate::analyze::{self, did_cache::DefIdCache};
use crate::chc;
use crate::refine::{self, TypeBuilder};
use crate::rty;

/// A `#[thrust::formula_fn]` definition, translated as the definition itself writes it.
///
/// The translation leaves the definition's type parameters standing, so what it yields is not yet
/// a [`chc::Formula`]: every sort it mentions is left to be built from the type arguments, and
/// both a `pre!`/`post!` application and a call to a predicate with several implementations only
/// name a contract once those arguments are known. [`FormulaFnDef::instantiate`] supplies them and
/// yields a [`FormulaFn`].
#[derive(Debug, Clone)]
pub struct FormulaFnDef<'tcx> {
    def_id: LocalDefId,
    params: IndexVec<rty::FunctionParamIdx, mir_ty::Ty<'tcx>>,
    param_idents: IndexVec<rty::FunctionParamIdx, Option<rustc_span::symbol::Ident>>,
    /// The type behind each sort the formula mentions, which names it as [`chc::Sort::Param`]
    /// carrying the type's index here.
    sort_tys: Vec<mir_ty::Ty<'tcx>>,
    formula: PolyFormula<'tcx>,
}

impl<'tcx> FormulaFnDef<'tcx> {
    pub fn instantiate(
        &self,
        analyzer: &analyze::Analyzer<'tcx>,
        generic_args: mir_ty::GenericArgsRef<'tcx>,
    ) -> FormulaFn<'tcx> {
        let cx = Instantiation::new(analyzer, self.def_id, generic_args);
        let params: IndexVec<_, _> = self
            .params
            .iter()
            .map(|ty| cx.instantiate_ty(*ty))
            .collect();
        let sorts: Vec<_> = self.sort_tys.iter().map(|ty| cx.build_sort(*ty)).collect();

        let mut formula = self.formula.clone();
        formula.instantiate_sort_params(&sorts);
        let param_values = cx.singleton_param_values(&params);
        let formula = formula
            .resolve(&cx)
            .subst_var(|idx: rty::FunctionParamIdx| {
                param_values[idx]
                    .clone()
                    .unwrap_or_else(|| chc::Term::var(idx))
            });

        FormulaFn {
            params,
            param_idents: self.param_idents.clone(),
            formula,
        }
    }
}

/// A [`FormulaFnDef`] with its definition's type parameters instantiated.
#[derive(Debug, Clone)]
pub struct FormulaFn<'tcx> {
    params: IndexVec<rty::FunctionParamIdx, mir_ty::Ty<'tcx>>,
    // TODO: remove once we stop relying on debug info to map parameters
    // `None` for a parameter bound by a pattern, as the closure upvars tuple is.
    param_idents: IndexVec<rty::FunctionParamIdx, Option<rustc_span::symbol::Ident>>,
    formula: chc::Formula<rty::FunctionParamIdx>,
}

impl<'a, D> Pretty<'a, D, termcolor::ColorSpec> for &FormulaFn<'_>
where
    D: pretty::DocAllocator<'a, termcolor::ColorSpec>,
    D::Doc: Clone,
{
    fn pretty(self, allocator: &'a D) -> pretty::DocBuilder<'a, D, termcolor::ColorSpec> {
        allocator
            .intersperse(
                self.params.iter_enumerated().map(|(idx, ty)| {
                    idx.pretty(allocator)
                        .append(": ")
                        .append(allocator.as_string(ty))
                }),
                ", ",
            )
            .enclose("|", "|")
            .group()
            .append(self.formula.pretty(allocator))
            .group()
    }
}

impl<'tcx> FormulaFn<'tcx> {
    pub fn formula(&self) -> &chc::Formula<rty::FunctionParamIdx> {
        &self.formula
    }

    pub fn params(&self) -> &IndexVec<rty::FunctionParamIdx, mir_ty::Ty<'tcx>> {
        &self.params
    }

    pub fn param_idents(
        &self,
    ) -> &IndexVec<rty::FunctionParamIdx, Option<rustc_span::symbol::Ident>> {
        &self.param_idents
    }

    pub fn to_require_formula(&self) -> chc::Formula<rty::FunctionParamIdx> {
        self.formula.clone()
    }

    /// Lowers an `ensures` formula function into a postcondition formula.
    ///
    /// Relies on the layout produced by `thrust_macros::ensures`: parameter `0`
    /// is the function's return value (bound to [`rty::RefinedTypeVar::Value`])
    /// and parameters `1..n` are the enclosing function's parameters in order
    /// (mapped to [`rty::RefinedTypeVar::Free`]).
    pub fn to_ensure_formula(&self) -> chc::Formula<rty::RefinedTypeVar<rty::FunctionParamIdx>> {
        self.formula.clone().map_var(|v| {
            if v.as_usize() == 0 {
                rty::RefinedTypeVar::Value
            } else {
                rty::RefinedTypeVar::Free(rty::FunctionParamIdx::from(v.as_usize() - 1))
            }
        })
    }

    /// Lowers a refinement-type formula function (generated by the `param` /
    /// `ret` / `sig` macros) into a [`rty::Refinement`].
    ///
    /// Relies on the layout produced by those macros: parameter `0` is the
    /// refinement's value binder (mapped to [`rty::RefinedTypeVar::Value`])
    /// and the remaining parameters carry the formula's free variables,
    /// mapped to [`rty::RefinedTypeVar::Free`].
    pub fn to_refinement(&self) -> rty::Refinement<rty::FunctionParamIdx> {
        self.formula
            .clone()
            .map_var(|v| {
                if v.as_usize() == 0 {
                    rty::RefinedTypeVar::Value
                } else {
                    rty::RefinedTypeVar::Free(rty::FunctionParamIdx::from(v.as_usize() - 1))
                }
            })
            .into()
    }
}

/// A formula whose sorts and whose contract-naming leaves are still open, awaiting the type
/// arguments of the definition it was translated from.
#[derive(Debug, Clone)]
enum PolyFormula<'tcx> {
    Closed(chc::Formula<rty::FunctionParamIdx>),
    ClosureSpec(ClosureSpec<'tcx>),
    Predicate(PredicateCall<'tcx>),
    Not(Box<PolyFormula<'tcx>>),
    And(Box<PolyFormula<'tcx>>, Box<PolyFormula<'tcx>>),
    Or(Box<PolyFormula<'tcx>>, Box<PolyFormula<'tcx>>),
    Implies(Box<PolyFormula<'tcx>>, Box<PolyFormula<'tcx>>),
    Exists(Vec<(String, chc::Sort)>, Box<PolyFormula<'tcx>>),
    Forall(Vec<(String, chc::Sort)>, Box<PolyFormula<'tcx>>),
}

impl<'tcx> PolyFormula<'tcx> {
    fn top() -> Self {
        PolyFormula::Closed(chc::Formula::top())
    }

    fn bottom() -> Self {
        PolyFormula::Closed(chc::Formula::bottom())
    }

    fn not(self) -> Self {
        match self {
            PolyFormula::Closed(fo) => PolyFormula::Closed(fo.not()),
            fo => PolyFormula::Not(Box::new(fo)),
        }
    }

    fn and(self, other: Self) -> Self {
        match (self, other) {
            (PolyFormula::Closed(lhs), PolyFormula::Closed(rhs)) => {
                PolyFormula::Closed(lhs.and(rhs))
            }
            (lhs, rhs) => PolyFormula::And(Box::new(lhs), Box::new(rhs)),
        }
    }

    fn or(self, other: Self) -> Self {
        match (self, other) {
            (PolyFormula::Closed(lhs), PolyFormula::Closed(rhs)) => {
                PolyFormula::Closed(lhs.or(rhs))
            }
            (lhs, rhs) => PolyFormula::Or(Box::new(lhs), Box::new(rhs)),
        }
    }

    fn implies(self, other: Self) -> Self {
        match (self, other) {
            (PolyFormula::Closed(lhs), PolyFormula::Closed(rhs)) => {
                PolyFormula::Closed(lhs.implies(rhs))
            }
            (lhs, rhs) => PolyFormula::Implies(Box::new(lhs), Box::new(rhs)),
        }
    }

    fn exists(vars: Vec<(String, chc::Sort)>, body: Self) -> Self {
        match body {
            PolyFormula::Closed(body) => PolyFormula::Closed(chc::Formula::exists(vars, body)),
            body => PolyFormula::Exists(vars, Box::new(body)),
        }
    }

    fn forall(vars: Vec<(String, chc::Sort)>, body: Self) -> Self {
        match body {
            PolyFormula::Closed(body) => PolyFormula::Closed(chc::Formula::forall(vars, body)),
            body => PolyFormula::Forall(vars, Box::new(body)),
        }
    }

    fn instantiate_sort_params(&mut self, sorts: &[chc::Sort]) {
        match self {
            PolyFormula::Closed(fo) => fo.instantiate_sort_params(sorts),
            PolyFormula::ClosureSpec(spec) => spec.instantiate_sort_params(sorts),
            PolyFormula::Predicate(call) => call.instantiate_sort_params(sorts),
            PolyFormula::Not(fo) => fo.instantiate_sort_params(sorts),
            PolyFormula::And(lhs, rhs)
            | PolyFormula::Or(lhs, rhs)
            | PolyFormula::Implies(lhs, rhs) => {
                lhs.instantiate_sort_params(sorts);
                rhs.instantiate_sort_params(sorts);
            }
            PolyFormula::Exists(vars, fo) | PolyFormula::Forall(vars, fo) => {
                for (_, sort) in vars {
                    sort.instantiate_params(sorts);
                }
                fo.instantiate_sort_params(sorts);
            }
        }
    }

    fn resolve(&self, cx: &Instantiation<'_, 'tcx>) -> chc::Formula<rty::FunctionParamIdx> {
        match self {
            PolyFormula::Closed(fo) => fo.clone(),
            PolyFormula::ClosureSpec(spec) => spec.resolve(cx),
            PolyFormula::Predicate(call) => call.resolve(cx),
            PolyFormula::Not(fo) => fo.resolve(cx).not(),
            PolyFormula::And(lhs, rhs) => lhs.resolve(cx).and(rhs.resolve(cx)),
            PolyFormula::Or(lhs, rhs) => lhs.resolve(cx).or(rhs.resolve(cx)),
            PolyFormula::Implies(lhs, rhs) => lhs.resolve(cx).implies(rhs.resolve(cx)),
            PolyFormula::Exists(vars, fo) => chc::Formula::exists(vars.clone(), fo.resolve(cx)),
            PolyFormula::Forall(vars, fo) => chc::Formula::forall(vars.clone(), fo.resolve(cx)),
        }
    }
}

/// A `pre!(f(..))` or `post!(f(..), result)` application.
///
/// It stands for one side of the contract of the closure the receiver denotes, which is the
/// closure the receiver's type names once the type parameters are instantiated.
#[derive(Debug, Clone)]
struct ClosureSpec<'tcx> {
    receiver_ty: mir_ty::Ty<'tcx>,
    receiver: chc::Term<rty::FunctionParamIdx>,
    args: Vec<chc::Term<rty::FunctionParamIdx>>,
    /// The value a postcondition constrains, or `None` for a precondition.
    result: Option<chc::Term<rty::FunctionParamIdx>>,
}

impl<'tcx> ClosureSpec<'tcx> {
    fn instantiate_sort_params(&mut self, sorts: &[chc::Sort]) {
        self.receiver.instantiate_sort_params(sorts);
        for arg in &mut self.args {
            arg.instantiate_sort_params(sorts);
        }
        if let Some(result) = &mut self.result {
            result.instantiate_sort_params(sorts);
        }
    }

    fn resolve(&self, cx: &Instantiation<'_, 'tcx>) -> chc::Formula<rty::FunctionParamIdx> {
        let side = if self.result.is_some() {
            "postcondition"
        } else {
            "precondition"
        };
        let receiver_ty = cx.instantiate_ty(self.receiver_ty);
        let fn_ty = cx
            .closure_fn_type(receiver_ty)
            .unwrap_or_else(|| panic!("{side} used on a non-closure parameter: {receiver_ty:?}"));
        // `fn_ty` is a closure (RustCall ABI), so its parameters are `[upvars, args..]`, where
        // the upvars are the closure value itself.
        assert_eq!(
            self.args.len(),
            fn_ty.params.len() - 1,
            "closure {side} arity mismatch: closure takes {} argument(s)",
            fn_ty.params.len() - 1
        );
        let param_args: Vec<_> =
            std::iter::once(cx.closure_receiver_term(receiver_ty, &fn_ty, self.receiver.clone()))
                .chain(self.args.iter().cloned())
                .collect();
        match &self.result {
            Some(result) => fn_ty.postcondition_formula(&param_args, result.clone()),
            None => fn_ty.precondition_formula(&param_args),
        }
    }
}

/// A call to a `#[thrust::predicate]` function.
///
/// A predicate declared by a trait has one definition per implementation, so the definition the
/// call names follows from the type arguments it is applied to.
#[derive(Debug, Clone)]
struct PredicateCall<'tcx> {
    def_id: DefId,
    generic_args: mir_ty::GenericArgsRef<'tcx>,
    args: Vec<chc::Term<rty::FunctionParamIdx>>,
}

impl<'tcx> PredicateCall<'tcx> {
    fn instantiate_sort_params(&mut self, sorts: &[chc::Sort]) {
        for arg in &mut self.args {
            arg.instantiate_sort_params(sorts);
        }
    }

    fn resolve(&self, cx: &Instantiation<'_, 'tcx>) -> chc::Formula<rty::FunctionParamIdx> {
        let generic_args = cx.instantiate_generic_args(self.generic_args);
        tracing::debug!(
            def_id = ?self.def_id,
            ?generic_args,
            "resolving predicate call in formula"
        );
        let instance = mir_ty::Instance::try_resolve(
            cx.tcx,
            mir_ty::TypingEnv::fully_monomorphized(),
            self.def_id,
            generic_args,
        )
        .unwrap();
        let def_id = instance.map_or(self.def_id, |instance| instance.def_id());
        let pred = refine::user_defined_pred(cx.tcx, def_id);
        chc::Formula::Atom(chc::Atom::new(pred.into(), self.args.clone()))
    }
}

/// The type arguments a [`FormulaFnDef`] is instantiated with, and the surroundings needed to read
/// the contracts they name.
struct Instantiation<'a, 'tcx> {
    analyzer: &'a analyze::Analyzer<'tcx>,
    tcx: TyCtxt<'tcx>,
    def_ids: DefIdCache<'tcx>,
    type_builder: TypeBuilder<'tcx>,
    generic_args: mir_ty::GenericArgsRef<'tcx>,
}

impl<'a, 'tcx> Instantiation<'a, 'tcx> {
    fn new(
        analyzer: &'a analyze::Analyzer<'tcx>,
        def_id: LocalDefId,
        generic_args: mir_ty::GenericArgsRef<'tcx>,
    ) -> Self {
        let tcx = analyzer.tcx();
        let def_ids = analyzer.def_ids();
        let type_builder = TypeBuilder::new(tcx, def_ids.clone(), def_id.to_def_id());
        Self {
            analyzer,
            tcx,
            def_ids,
            type_builder,
            generic_args,
        }
    }

    fn instantiate_ty(&self, ty: mir_ty::Ty<'tcx>) -> mir_ty::Ty<'tcx> {
        mir_ty::EarlyBinder::bind(ty).instantiate(self.tcx, self.generic_args)
    }

    fn build_sort(&self, ty: mir_ty::Ty<'tcx>) -> chc::Sort {
        self.type_builder.build(self.instantiate_ty(ty)).to_sort()
    }

    fn instantiate_generic_args(
        &self,
        generic_args: mir_ty::GenericArgsRef<'tcx>,
    ) -> mir_ty::GenericArgsRef<'tcx> {
        mir_ty::EarlyBinder::bind(generic_args).instantiate(self.tcx, self.generic_args)
    }

    /// The value each parameter whose sort holds exactly one element takes.
    ///
    /// The analyzer does not give such a parameter a variable of its own, so a formula names its
    /// value directly instead.
    // FIXME: fix the analyzer side to uniformly accept all params
    fn singleton_param_values(
        &self,
        params: &IndexVec<rty::FunctionParamIdx, mir_ty::Ty<'tcx>>,
    ) -> IndexVec<rty::FunctionParamIdx, Option<chc::Term<rty::FunctionParamIdx>>> {
        params
            .iter()
            .map(|ty| {
                let ty = self
                    .tcx
                    .normalize_erasing_regions(mir_ty::TypingEnv::fully_monomorphized(), *ty);
                // `at_entry()` yields the `Inner` of a `FnParam<Inner>`; classify by it so
                // a singleton wrapped argument collapses like any other singleton below.
                let repr_ty = self.fn_param_wrapper_inner_ty(ty).unwrap_or(ty);
                let ty = self.type_builder.build(repr_ty);
                ty.to_sort()
                    .is_singleton()
                    .then(|| singleton_term_for_ty(&ty).unwrap())
            })
            .collect()
    }

    /// The `Inner` of a `thrust_models::FnParam<Inner>` wrapper type, if `ty` is one.
    fn fn_param_wrapper_inner_ty(&self, ty: mir_ty::Ty<'tcx>) -> Option<mir_ty::Ty<'tcx>> {
        match ty.kind() {
            mir_ty::TyKind::Adt(def, args)
                if Some(def.did()) == self.def_ids.fn_param_wrapper() =>
            {
                Some(args.type_at(0))
            }
            _ => None,
        }
    }

    /// The closure type a `pre!`/`post!` receiver of type `ty` reaches, if any.
    fn closure_ty(&self, ty: mir_ty::Ty<'tcx>) -> Option<mir_ty::Ty<'tcx>> {
        let inner = match ty.kind() {
            mir_ty::TyKind::Adt(adt, args) if Some(adt.did()) == self.def_ids.mut_model() => {
                args.type_at(0)
            }
            mir_ty::TyKind::Ref(_, inner_ty, mir_ty::Mutability::Not) => *inner_ty,
            _ => ty,
        };
        match inner.kind() {
            mir_ty::TyKind::Adt(adt, args) if Some(adt.did()) == self.def_ids.closure_model() => {
                Some(args.type_at(0))
            }
            _ => None,
        }
    }

    /// Resolves the [`rty::FunctionType`] of the closure contract referred to by a receiver of
    /// type `ty`, as collected by the analyzer.
    fn closure_fn_type(&self, ty: mir_ty::Ty<'tcx>) -> Option<rty::FunctionType> {
        let closure_ty = self.closure_ty(ty)?;
        let mir_ty::TyKind::Closure(def_id, args) = closure_ty.kind() else {
            return None;
        };
        self.analyzer
            .known_function_ty_with_args(*def_id, self.tcx.mk_args(args.as_closure().parent_args()))
    }

    /// The receiver term as the closure's own body takes it.
    ///
    /// That body takes the upvars by `&`, by `&mut`, or by value, following the kind inferred
    /// for the closure, while `pre!`/`post!` reach the closure through the parameter the
    /// annotated function declares. A call bridges the two by borrowing the closure into the
    /// receiver the body takes; the same borrow is taken here on the term.
    fn closure_receiver_term(
        &self,
        receiver_ty: mir_ty::Ty<'tcx>,
        fn_ty: &rty::FunctionType,
        term: chc::Term<rty::FunctionParamIdx>,
    ) -> chc::Term<rty::FunctionParamIdx> {
        let held_as = match receiver_ty.kind() {
            mir_ty::TyKind::Adt(adt, _) if Some(adt.did()) == self.def_ids.mut_model() => {
                Some(rty::RefKind::Mut)
            }
            mir_ty::TyKind::Ref(_, _, mir_ty::Mutability::Not) => Some(rty::RefKind::Immut),
            _ => None,
        };
        let upvars_ty = &fn_ty.params[rty::FunctionParamIdx::from(0usize)].ty;
        let received_as = match upvars_ty.as_pointer().map(|ty| ty.kind) {
            Some(rty::PointerKind::Ref(kind)) => Some(kind),
            _ => None,
        };

        match (held_as, received_as) {
            (None, Some(rty::RefKind::Immut)) => chc::Term::box_(term),
            (None, Some(rty::RefKind::Mut)) => chc::Term::mut_(term.clone(), term),
            (Some(rty::RefKind::Mut), Some(rty::RefKind::Immut)) => {
                chc::Term::box_(term.mut_current())
            }
            _ => term,
        }
    }
}

/// The one value a type whose sort holds exactly one takes, or `None` for any other type.
fn singleton_term_for_ty(ty: &rty::Type<rty::Closed>) -> Option<chc::Term<rty::FunctionParamIdx>> {
    match ty {
        rty::Type::String | rty::Type::Never | rty::Type::Function(_) => Some(chc::Term::null()),
        rty::Type::Tuple(ty) => ty
            .elems
            .iter()
            .map(|elem| singleton_term_for_ty(&elem.ty))
            .collect::<Option<Vec<_>>>()
            .map(chc::Term::tuple),
        rty::Type::Pointer(ty) => {
            let elem = singleton_term_for_ty(&ty.elem.ty)?;
            match ty.kind {
                rty::PointerKind::Own | rty::PointerKind::Ref(rty::RefKind::Immut) => {
                    Some(chc::Term::box_(elem))
                }
                rty::PointerKind::Ref(rty::RefKind::Mut) => {
                    Some(chc::Term::mut_(elem.clone(), elem))
                }
            }
        }
        rty::Type::Array(ty) => {
            if singleton_term_for_ty(&ty.elem.ty).is_some() {
                panic!("singleton array type is not supported in formula: {:?}", ty);
            }
            None
        }
        _ => None,
    }
}

#[derive(Debug, Clone, Copy)]
enum AmbiguousBinOp {
    Eq,
    Ne,
    Ge,
    Le,
    Gt,
    Lt,
}

#[derive(Debug, Clone)]
enum FormulaOrTerm<'tcx> {
    Formula(PolyFormula<'tcx>),
    Term(chc::Term<rty::FunctionParamIdx>),
    BinOp(
        chc::Term<rty::FunctionParamIdx>,
        AmbiguousBinOp,
        chc::Term<rty::FunctionParamIdx>,
    ),
    And(Box<FormulaOrTerm<'tcx>>, Box<FormulaOrTerm<'tcx>>),
    Or(Box<FormulaOrTerm<'tcx>>, Box<FormulaOrTerm<'tcx>>),
    Implies(Box<FormulaOrTerm<'tcx>>, Box<FormulaOrTerm<'tcx>>),
    Not(Box<FormulaOrTerm<'tcx>>),
    Literal(bool),
}

impl<'tcx> FormulaOrTerm<'tcx> {
    fn into_formula(self) -> Option<PolyFormula<'tcx>> {
        let fo = match self {
            FormulaOrTerm::Formula(fo) => fo,
            FormulaOrTerm::Term { .. } => return None,
            FormulaOrTerm::BinOp(lhs, binop, rhs) => {
                let pred = match binop {
                    AmbiguousBinOp::Eq => chc::KnownPred::EQUAL,
                    AmbiguousBinOp::Ne => chc::KnownPred::NOT_EQUAL,
                    AmbiguousBinOp::Ge => chc::KnownPred::GREATER_THAN_OR_EQUAL,
                    AmbiguousBinOp::Le => chc::KnownPred::LESS_THAN_OR_EQUAL,
                    AmbiguousBinOp::Gt => chc::KnownPred::GREATER_THAN,
                    AmbiguousBinOp::Lt => chc::KnownPred::LESS_THAN,
                };
                PolyFormula::Closed(chc::Formula::Atom(chc::Atom::new(
                    pred.into(),
                    vec![lhs, rhs],
                )))
            }
            FormulaOrTerm::And(lhs, rhs) => lhs.into_formula()?.and(rhs.into_formula()?),
            FormulaOrTerm::Or(lhs, rhs) => lhs.into_formula()?.or(rhs.into_formula()?),
            FormulaOrTerm::Implies(lhs, rhs) => lhs.into_formula()?.implies(rhs.into_formula()?),
            FormulaOrTerm::Not(formula_or_term) => formula_or_term.into_formula()?.not(),
            FormulaOrTerm::Literal(b) => {
                if b {
                    PolyFormula::top()
                } else {
                    PolyFormula::bottom()
                }
            }
        };
        Some(fo)
    }

    fn into_term(self) -> Option<chc::Term<rty::FunctionParamIdx>> {
        let t = match self {
            FormulaOrTerm::Formula { .. } => return None,
            FormulaOrTerm::Term(t) => t,
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Eq, rhs) => lhs.eq(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Ne, rhs) => lhs.ne(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Ge, rhs) => lhs.ge(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Le, rhs) => lhs.le(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Gt, rhs) => lhs.gt(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Lt, rhs) => lhs.lt(rhs),
            FormulaOrTerm::And(lhs, rhs) => lhs.into_term()?.and(rhs.into_term()?),
            FormulaOrTerm::Or(lhs, rhs) => lhs.into_term()?.or(rhs.into_term()?),
            FormulaOrTerm::Implies(lhs, rhs) => lhs.into_term()?.not().or(rhs.into_term()?),
            FormulaOrTerm::Not(formula_or_term) => formula_or_term.into_term()?.not(),
            FormulaOrTerm::Literal(b) => chc::Term::bool(b),
        };
        Some(t)
    }
}

/// Translates the body of a `#[thrust::formula_fn]` definition into a [`FormulaFnDef`].
#[derive(Clone)]
pub struct AnnotFnTranslator<'tcx> {
    tcx: TyCtxt<'tcx>,
    local_def_id: LocalDefId,

    typeck: &'tcx mir_ty::TypeckResults<'tcx>,
    body: &'tcx rustc_hir::Body<'tcx>,
    typing_env: mir_ty::TypingEnv<'tcx>,

    def_ids: DefIdCache<'tcx>,
    /// The types the sorts handed out by [`AnnotFnTranslator::sort_of`] stand for, shared with
    /// the translators of nested quantifier bodies.
    sort_tys: Rc<RefCell<Vec<mir_ty::Ty<'tcx>>>>,
    env: HashMap<HirId, chc::Term<rty::FunctionParamIdx>>,
}

impl<'tcx> AnnotFnTranslator<'tcx> {
    pub fn new(tcx: TyCtxt<'tcx>, def_ids: DefIdCache<'tcx>, local_def_id: LocalDefId) -> Self {
        let body = tcx.hir_body_owned_by(local_def_id);
        let typeck = tcx.typeck(local_def_id);
        let typing_env = mir_ty::TypingEnv::post_analysis(tcx, local_def_id);
        let mut translator = Self {
            tcx,
            local_def_id,
            typeck,
            body,
            typing_env,
            def_ids,
            sort_tys: Default::default(),
            env: HashMap::default(),
        };
        translator.build_env_from_params();
        translator
    }

    /// The sort of `ty`, which the formula names as a [`chc::Sort::Param`] so that it is built
    /// once the definition's type arguments are known.
    fn sort_of(&self, ty: mir_ty::Ty<'tcx>) -> chc::Sort {
        let mut sort_tys = self.sort_tys.borrow_mut();
        sort_tys.push(self.normalize(ty));
        chc::Sort::param(sort_tys.len() - 1)
    }

    fn build_env_from_params(&mut self) {
        for (idx, param) in self.body.params.iter().enumerate() {
            let param_idx = rty::FunctionParamIdx::from(idx);
            if self.is_closure_upvars_param(param) {
                self.build_env_from_captures(chc::Term::var(param_idx), param.pat);
                continue;
            }
            self.build_env_from_pat(chc::Term::var(param_idx), param.pat);
        }
    }

    /// Whether the parameter holds the closure's upvars, as marked by
    /// `#[thrust::closure_upvars]` on a `closure!` specification.
    fn is_closure_upvars_param(&self, param: &rustc_hir::Param<'tcx>) -> bool {
        let attr_path = analyze::annot::closure_upvars_path();
        self.tcx
            .hir_attrs(param.hir_id)
            .iter()
            .any(|attr| attr.path_matches(&attr_path))
    }

    /// Binds the names of a closure specification's upvars pattern to the closure's
    /// captured variables.
    ///
    /// The pattern lists the captures a clause names, in the order it wrote them,
    /// while the upvars hold every capture in the order rustc chose. The two are
    /// therefore matched up by name.
    fn build_env_from_captures(
        &mut self,
        upvars_term: chc::Term<rty::FunctionParamIdx>,
        pat: &'tcx rustc_hir::Pat<'tcx>,
    ) {
        let rustc_hir::PatKind::Tuple(subpats, _) = pat.kind else {
            panic!(
                "closure upvars are expected to be a tuple pattern: {:?}",
                pat
            );
        };
        let closure_def_id = self.tcx.local_parent(self.local_def_id);
        let captures = self.tcx.closure_captures(closure_def_id);
        let closure_ty = self.tcx.type_of(closure_def_id).instantiate_identity();
        let mir_ty::TyKind::Closure(_, closure_args) = closure_ty.kind() else {
            panic!("closure specification is expected to sit inside a closure");
        };
        let mut upvar_terms = Vec::new();
        for i in 0..captures.len() {
            let upvar_term = match closure_args.as_closure().kind() {
                mir_ty::ClosureKind::Fn => upvars_term.clone().box_current().tuple_proj(i),
                mir_ty::ClosureKind::FnMut => chc::Term::mut_(
                    upvars_term.clone().mut_current().tuple_proj(i),
                    upvars_term.clone().mut_final().tuple_proj(i),
                ),
                mir_ty::ClosureKind::FnOnce => upvars_term.clone().tuple_proj(i),
            };
            upvar_terms.push(upvar_term);
        }
        for subpat in subpats {
            let rustc_hir::PatKind::Binding(_, hir_id, ident, None) = subpat.kind else {
                panic!("closure capture is expected to be a binding: {:?}", subpat);
            };
            let Some(idx) = captures.iter().position(|capture| {
                capture.var_ident.name == ident.name && capture.place.projections.is_empty()
            }) else {
                self.tcx.dcx().span_fatal(
                    subpat.span,
                    format!("`{}` is not captured by this closure", ident),
                );
            };
            self.env.insert(hir_id, upvar_terms[idx].clone());
        }
    }

    fn build_env_from_pat(
        &mut self,
        param: chc::Term<rty::FunctionParamIdx>,
        pat: &'tcx rustc_hir::Pat<'tcx>,
    ) {
        use rustc_hir::PatKind;

        match pat.kind {
            PatKind::Binding(_, hir_id, _, None) => {
                self.env.insert(hir_id, param);
            }
            PatKind::TupleStruct(_, subpats, _) | PatKind::Tuple(subpats, _) => {
                for (idx, subpat) in subpats.iter().enumerate() {
                    let field_term = param.clone().tuple_proj(idx);
                    self.build_env_from_pat(field_term, subpat);
                }
            }
            _ => unimplemented!("unsupported pattern in formula: {:?}", pat),
        }
    }

    /// Normalizes a type of this definition, which still mentions the definition's type
    /// parameters, as far as they allow.
    fn normalize(&self, ty: mir_ty::Ty<'tcx>) -> mir_ty::Ty<'tcx> {
        self.tcx
            .try_normalize_erasing_regions(self.typing_env, ty)
            .unwrap_or(ty)
    }

    fn expr_ty(&self, expr: &'tcx rustc_hir::Expr<'tcx>) -> mir_ty::Ty<'tcx> {
        self.normalize(self.typeck.expr_ty(expr))
    }

    pub fn to_formula_fn_def(&self) -> FormulaFnDef<'tcx> {
        let formula = self.to_formula(self.body.value);
        let params = self
            .tcx
            .fn_sig(self.local_def_id.to_def_id())
            .instantiate_identity()
            .skip_binder()
            .inputs()
            .to_vec();
        let param_idents = self
            .tcx
            .fn_arg_idents(self.local_def_id.to_def_id())
            .iter()
            .copied()
            .collect();
        FormulaFnDef {
            def_id: self.local_def_id,
            params: IndexVec::from_raw(params),
            param_idents,
            sort_tys: self.sort_tys.borrow().clone(),
            formula,
        }
    }

    fn to_formula(&self, hir: &'tcx rustc_hir::Expr<'tcx>) -> PolyFormula<'tcx> {
        self.to_formula_or_term(hir)
            .into_formula()
            .expect("expected a formula")
    }

    fn to_term(&self, hir: &'tcx rustc_hir::Expr<'tcx>) -> chc::Term<rty::FunctionParamIdx> {
        self.to_formula_or_term(hir)
            .into_term()
            .expect("expected a term")
    }

    /// Extracts the logical argument terms passed to `closure_precondition`/
    /// `closure_postcondition`. The arguments are supplied as a single tuple (e.g. `(x,)` or
    /// `()`), whose elements are the logical arguments of the closure.
    fn closure_spec_args(
        &self,
        arg: &'tcx rustc_hir::Expr<'tcx>,
    ) -> Vec<chc::Term<rty::FunctionParamIdx>> {
        match arg.kind {
            rustc_hir::ExprKind::Tup(elems) => elems.iter().map(|e| self.to_term(e)).collect(),
            _ => vec![self.to_term(arg)],
        }
    }

    fn translate_closure_spec(
        &self,
        receiver: &'tcx rustc_hir::Expr<'tcx>,
        args: &'tcx rustc_hir::Expr<'tcx>,
        result: Option<&'tcx rustc_hir::Expr<'tcx>>,
    ) -> FormulaOrTerm<'tcx> {
        FormulaOrTerm::Formula(PolyFormula::ClosureSpec(ClosureSpec {
            receiver_ty: self.expr_ty(receiver),
            receiver: self.to_term(receiver),
            args: self.closure_spec_args(args),
            result: result.map(|result| self.to_term(result)),
        }))
    }

    fn node_arg_sort_at(&self, hir_id: HirId, idx: usize) -> chc::Sort {
        self.sort_of(self.typeck.node_args(hir_id).type_at(idx))
    }

    fn adt_arg_sort_at(&self, expr: &'tcx rustc_hir::Expr<'tcx>, idx: usize) -> chc::Sort {
        let mir_ty::TyKind::Adt(_, args) = self.expr_ty(expr).kind() else {
            panic!("expected ADT");
        };
        self.sort_of(args.type_at(idx))
    }

    fn variant_ctor_term(
        &self,
        ctor_did: rustc_span::def_id::DefId,
        result_ty: mir_ty::Ty<'tcx>,
        field_terms: Vec<chc::Term<rty::FunctionParamIdx>>,
    ) -> chc::Term<rty::FunctionParamIdx> {
        let variant_did = self.tcx.parent(ctor_did);
        let adt_did = self.tcx.parent(variant_did);
        let d_sym = crate::refine::datatype_symbol(self.tcx, adt_did);
        let variant_name = self.tcx.item_name(variant_did);
        let v_sym = chc::DatatypeSymbol::new(format!("{}.{}", d_sym, variant_name));
        let sort_args = if let mir_ty::TyKind::Adt(_, generic_args) = result_ty.kind() {
            generic_args.types().map(|ty| self.sort_of(ty)).collect()
        } else {
            panic!("expected an ADT type for variant constructor")
        };
        chc::Term::datatype_ctor(d_sym, sort_args, v_sym, field_terms)
    }

    fn to_formula_with_quantified_vars(
        &self,
        closure: &rustc_hir::Body<'tcx>,
    ) -> (Vec<(String, chc::Sort)>, PolyFormula<'tcx>) {
        let mut inner_translator = self.clone();
        let mut vars = Vec::new();
        for param in closure.params {
            let rustc_hir::PatKind::Binding(_, hir_id, ident, None) = param.pat.kind else {
                panic!(
                    "exists/forall closure parameter must be a simple binding: {:?}",
                    param.pat
                );
            };
            let sort = self.sort_of(self.typeck.pat_ty(param.pat));
            let var_term = chc::Term::FormulaQuantifiedVar(sort.clone(), ident.name.to_string());
            inner_translator.env.insert(hir_id, var_term);
            vars.push((ident.name.to_string(), sort));
        }
        let body_formula = inner_translator.to_formula(closure.value);
        (vars, body_formula)
    }

    fn to_formula_or_term(&self, hir: &'tcx rustc_hir::Expr<'tcx>) -> FormulaOrTerm<'tcx> {
        use rustc_hir::ExprKind;

        match hir.kind {
            ExprKind::Binary(op, lhs, rhs) => {
                match op.node {
                    rustc_hir::BinOpKind::Or => {
                        let lhs = self.to_formula_or_term(lhs);
                        let rhs = self.to_formula_or_term(rhs);
                        return FormulaOrTerm::Or(lhs.into(), rhs.into());
                    }
                    rustc_hir::BinOpKind::And => {
                        let lhs = self.to_formula_or_term(lhs);
                        let rhs = self.to_formula_or_term(rhs);
                        return FormulaOrTerm::And(lhs.into(), rhs.into());
                    }
                    rustc_hir::BinOpKind::Add => {
                        let lhs = self.to_term(lhs);
                        let rhs = self.to_term(rhs);
                        return FormulaOrTerm::Term(lhs.add(rhs));
                    }
                    rustc_hir::BinOpKind::Sub => {
                        let lhs = self.to_term(lhs);
                        let rhs = self.to_term(rhs);
                        return FormulaOrTerm::Term(lhs.sub(rhs));
                    }
                    rustc_hir::BinOpKind::Mul => {
                        let lhs = self.to_term(lhs);
                        let rhs = self.to_term(rhs);
                        return FormulaOrTerm::Term(lhs.mul(rhs));
                    }
                    _ => {}
                }

                let binop = match op.node {
                    rustc_hir::BinOpKind::Eq => AmbiguousBinOp::Eq,
                    rustc_hir::BinOpKind::Ne => AmbiguousBinOp::Ne,
                    rustc_hir::BinOpKind::Ge => AmbiguousBinOp::Ge,
                    rustc_hir::BinOpKind::Le => AmbiguousBinOp::Le,
                    rustc_hir::BinOpKind::Gt => AmbiguousBinOp::Gt,
                    rustc_hir::BinOpKind::Lt => AmbiguousBinOp::Lt,
                    _ => unimplemented!("unsupported binary operator in formula: {:?}", op),
                };
                let lhs = self.to_formula_or_term(lhs);
                let rhs = self.to_formula_or_term(rhs);
                FormulaOrTerm::BinOp(lhs.into_term().unwrap(), binop, rhs.into_term().unwrap())
            }
            ExprKind::Unary(op, operand) => match op {
                rustc_hir::UnOp::Neg => {
                    let operand = self.to_term(operand);
                    FormulaOrTerm::Term(operand.neg())
                }
                rustc_hir::UnOp::Not => {
                    let operand_ty = self.expr_ty(operand);
                    match operand_ty.ty_adt_def() {
                        Some(adt) if Some(adt.did()) == self.def_ids.mut_model() => {
                            let operand = self.to_term(operand);
                            FormulaOrTerm::Term(operand.mut_final())
                        }
                        _ => {
                            let operand = self.to_formula_or_term(operand);
                            FormulaOrTerm::Not(Box::new(operand))
                        }
                    }
                }
                rustc_hir::UnOp::Deref => {
                    let operand_ty = self.expr_ty(operand);
                    let term = self.to_term(operand);
                    if matches!(
                        operand_ty.kind(),
                        mir_ty::TyKind::Ref(_, _, mir_ty::Mutability::Not)
                    ) {
                        return FormulaOrTerm::Term(term.box_current());
                    }
                    let adt = operand_ty
                        .ty_adt_def()
                        .expect("deref operand must be a model type");
                    if Some(adt.did()) == self.def_ids.mut_model() {
                        FormulaOrTerm::Term(term.mut_current())
                    } else if Some(adt.did()) == self.def_ids.box_model() {
                        FormulaOrTerm::Term(term.box_current())
                    } else {
                        unimplemented!(
                            "unsupported deref operand type in formula: {:?}",
                            operand_ty
                        )
                    }
                }
            },
            ExprKind::AddrOf(rustc_hir::BorrowKind::Ref, rustc_hir::Mutability::Not, operand) => {
                let operand = self.to_term(operand);
                FormulaOrTerm::Term(operand.boxed())
            }
            ExprKind::Lit(lit) => match lit.node {
                rustc_ast::LitKind::Int(i, _) => {
                    let n = i64::try_from(i.get())
                        .expect("integer literal out of i64 range in formula");
                    FormulaOrTerm::Term(chc::Term::int(n))
                }
                rustc_ast::LitKind::Bool(b) => FormulaOrTerm::Literal(b),
                _ => unimplemented!("unsupported literal in formula: {:?}", lit),
            },
            ExprKind::Path(qpath) => match self.typeck.qpath_res(&qpath, hir.hir_id) {
                rustc_hir::def::Res::Local(hir_id) => FormulaOrTerm::Term(
                    self.env
                        .get(&hir_id)
                        .expect("unbound variable in formula")
                        .clone(),
                ),
                rustc_hir::def::Res::Def(
                    rustc_hir::def::DefKind::Ctor(rustc_hir::def::CtorOf::Variant, _),
                    ctor_did,
                ) => {
                    FormulaOrTerm::Term(self.variant_ctor_term(ctor_did, self.expr_ty(hir), vec![]))
                }
                _ => unimplemented!("unsupported path in formula: {:?}", qpath),
            },
            ExprKind::Tup(exprs) => {
                let terms = exprs.iter().map(|e| self.to_term(e)).collect();
                FormulaOrTerm::Term(chc::Term::tuple(terms))
            }
            ExprKind::Struct(_qpath, fields, tail) => {
                if !matches!(tail, rustc_hir::StructTailExpr::None) {
                    unimplemented!("struct update syntax is not supported in formulas");
                }
                let adt = self
                    .expr_ty(hir)
                    .ty_adt_def()
                    .expect("struct literal on a non-ADT type");
                let mut terms = Vec::new();
                let variant = adt.non_enum_variant();
                for variant_field in &variant.fields {
                    let Some(field) = fields.iter().find(|f| f.ident.name == variant_field.name)
                    else {
                        self.tcx.dcx().span_fatal(
                            hir.span,
                            format!("missing field `{}` in struct literal", variant_field.name),
                        );
                    };
                    terms.push(self.to_term(field.expr));
                }
                FormulaOrTerm::Term(chc::Term::tuple(terms))
            }
            ExprKind::Field(expr, field) => {
                // Tuples use numeric field names (`.0`); structs (represented as
                // tuples in the logic) use named fields resolved to their position.
                let index = match field.name.as_str().parse::<usize>() {
                    Ok(index) => index,
                    Err(_) => {
                        let adt = self
                            .expr_ty(expr)
                            .ty_adt_def()
                            .expect("named field access on a non-ADT type");
                        adt.non_enum_variant()
                            .fields
                            .iter()
                            .position(|f| f.name == field.name)
                            .expect("unknown named field in formula")
                    }
                };
                let term = self.to_term(expr);
                FormulaOrTerm::Term(term.tuple_proj(index))
            }
            ExprKind::Index(array, index, _) => {
                let array_ty = self.expr_ty(array);
                let array_term = self.to_term(array);
                let index_term = self.to_term(index);
                let is_seq = array_ty
                    .ty_adt_def()
                    .is_some_and(|adt| Some(adt.did()) == self.def_ids.seq_model());
                let array_inner = if is_seq {
                    array_term.tuple_proj(0)
                } else {
                    array_term
                };
                FormulaOrTerm::Term(array_inner.select(index_term))
            }
            ExprKind::MethodCall(method, receiver, args, _) => {
                if let Some(def_id) = self.typeck.type_dependent_def_id(hir.hir_id) {
                    if Some(def_id) == self.def_ids.array_model_store() {
                        assert_eq!(args.len(), 2, "array_store takes exactly 2 arguments");
                        let array_term = self.to_term(receiver);
                        let index_term = self.to_term(&args[0]);
                        let value_term = self.to_term(&args[1]);
                        return FormulaOrTerm::Term(array_term.store(index_term, value_term));
                    }
                    if Some(def_id) == self.def_ids.fn_param_at_entry() {
                        assert!(
                            args.is_empty(),
                            "FnParam::at_entry does not take any arguments"
                        );
                        let t = self.to_term(receiver);
                        return FormulaOrTerm::Term(t);
                    }
                    if Some(def_id) == self.def_ids.seq_len() {
                        assert!(args.is_empty(), "Seq::len does not take any arguments");
                        let t = self.to_term(receiver);
                        return FormulaOrTerm::Term(t.tuple_proj(1));
                    }
                    if Some(def_id) == self.def_ids.seq_push() {
                        assert_eq!(args.len(), 1, "Seq::push takes exactly 1 argument");
                        let t = self.to_term(receiver);
                        let v = self.to_term(&args[0]);
                        let arr = t.clone().tuple_proj(0);
                        let len = t.tuple_proj(1);
                        let new_arr = arr.store(len.clone(), v);
                        let new_len = len.add(chc::Term::int(1));
                        return FormulaOrTerm::Term(chc::Term::tuple(vec![new_arr, new_len]));
                    }
                    if Some(def_id) == self.def_ids.seq_concat() {
                        assert_eq!(args.len(), 1, "Seq::concat takes exactly 1 argument");
                        let elem_sort = self.adt_arg_sort_at(receiver, 0);
                        let t = self.to_term(receiver);
                        let other = self.to_term(&args[0]);
                        let a_len = t.clone().tuple_proj(1);
                        let b_len = other.clone().tuple_proj(1);
                        let new_arr = chc::Term::seq_concat(elem_sort, t, other);
                        let new_len = a_len.add(b_len);
                        return FormulaOrTerm::Term(chc::Term::tuple(vec![new_arr, new_len]));
                    }
                }
                unimplemented!("unsupported method call in formula: {:?}", method)
            }
            ExprKind::Call(func_expr, args) => {
                if let ExprKind::Path(qpath) = &func_expr.kind {
                    let res = self.typeck.qpath_res(qpath, func_expr.hir_id);
                    if let rustc_hir::def::Res::Def(def_kind, def_id) = res {
                        if Some(def_id) == self.def_ids.closure_precondition() {
                            let [receiver, args] = args else {
                                panic!(
                                    "closure_precondition takes a closure and a tuple of arguments"
                                );
                            };
                            return self.translate_closure_spec(receiver, args, None);
                        }
                        if Some(def_id) == self.def_ids.closure_postcondition() {
                            let [receiver, args, result] = args else {
                                panic!(
                                    "closure_postcondition takes a closure, a tuple of arguments, and a result"
                                );
                            };
                            return self.translate_closure_spec(receiver, args, Some(result));
                        }
                        if Some(def_id) == self.def_ids.exists() {
                            assert_eq!(args.len(), 1, "exists takes exactly 1 argument");
                            let ExprKind::Closure(closure) = args[0].kind else {
                                panic!("exists argument must be a closure");
                            };
                            let closure_body = self.tcx.hir_body(closure.body);

                            let (vars, body_formula) =
                                self.to_formula_with_quantified_vars(closure_body);
                            return FormulaOrTerm::Formula(PolyFormula::exists(vars, body_formula));
                        }
                        if Some(def_id) == self.def_ids.forall() {
                            assert_eq!(args.len(), 1, "forall takes exactly 1 argument");
                            let ExprKind::Closure(closure) = args[0].kind else {
                                panic!("forall argument must be a closure");
                            };
                            let closure_body = self.tcx.hir_body(closure.body);

                            let (vars, body_formula) =
                                self.to_formula_with_quantified_vars(closure_body);
                            return FormulaOrTerm::Formula(PolyFormula::forall(vars, body_formula));
                        }
                        if Some(def_id) == self.def_ids.fn_param_at_entry() {
                            assert_eq!(args.len(), 1, "FnParam::at_entry takes exactly 1 argument");
                            let t = self.to_term(&args[0]);
                            return FormulaOrTerm::Term(t);
                        }
                        if Some(def_id) == self.def_ids.implies() {
                            let [lhs, rhs] = args else {
                                panic!("implies takes exactly 2 arguments");
                            };
                            let lhs = self.to_formula_or_term(lhs);
                            let rhs = self.to_formula_or_term(rhs);
                            return FormulaOrTerm::Implies(lhs.into(), rhs.into());
                        }
                        if Some(def_id) == self.def_ids.mut_model_new() {
                            assert_eq!(args.len(), 2, "Mut::new takes exactly 2 arguments");
                            let t1 = self.to_term(&args[0]);
                            let t2 = self.to_term(&args[1]);
                            return FormulaOrTerm::Term(chc::Term::mut_(t1, t2));
                        }
                        if Some(def_id) == self.def_ids.box_model_new() {
                            assert_eq!(args.len(), 1, "Box::new takes exactly 1 argument");
                            let t = self.to_term(&args[0]);
                            return FormulaOrTerm::Term(chc::Term::box_(t));
                        }
                        if Some(def_id) == self.def_ids.seq_empty() {
                            assert!(args.is_empty(), "Seq::empty does not take any arguments");
                            let elem_sort = self.node_arg_sort_at(func_expr.hir_id, 0);
                            return FormulaOrTerm::Term(chc::Term::tuple(vec![
                                chc::Term::array_empty(chc::Sort::int(), elem_sort),
                                chc::Term::int(0),
                            ]));
                        }
                        if Some(def_id) == self.def_ids.seq_singleton() {
                            assert_eq!(args.len(), 1, "Seq::singleton takes exactly 1 argument");
                            let v = self.to_term(&args[0]);
                            let elem_sort = self.node_arg_sort_at(func_expr.hir_id, 0);
                            let new_arr = chc::Term::array_empty(chc::Sort::int(), elem_sort)
                                .store(chc::Term::int(0), v);
                            return FormulaOrTerm::Term(chc::Term::tuple(vec![
                                new_arr,
                                chc::Term::int(1),
                            ]));
                        }
                        if let rustc_hir::def::DefKind::Ctor(ctor_of, _) = def_kind {
                            let terms = args.iter().map(|e| self.to_term(e)).collect();
                            match ctor_of {
                                rustc_hir::def::CtorOf::Variant => {
                                    return FormulaOrTerm::Term(self.variant_ctor_term(
                                        def_id,
                                        self.expr_ty(hir),
                                        terms,
                                    ));
                                }
                                rustc_hir::def::CtorOf::Struct => {
                                    return FormulaOrTerm::Term(chc::Term::tuple(terms));
                                }
                            }
                        }
                        if self
                            .tcx
                            .get_attrs_by_path(def_id, &analyze::annot::predicate_path())
                            .next()
                            .is_some()
                        {
                            return FormulaOrTerm::Formula(PolyFormula::Predicate(PredicateCall {
                                def_id,
                                generic_args: self.typeck.node_args(func_expr.hir_id),
                                args: args.iter().map(|e| self.to_term(e)).collect(),
                            }));
                        }
                    }
                }
                unimplemented!("unsupported call in formula: {:?}", func_expr)
            }
            ExprKind::Block(block, _) => {
                if block.stmts.is_empty() {
                    self.to_formula_or_term(block.expr.expect("expected an expression in block"))
                } else {
                    unimplemented!("unsupported block in formula: {:?}", block);
                }
            }
            _ => unimplemented!("unsupported expression in formula: {:?}", hir),
        }
    }
}
