use std::collections::HashMap;

use pretty::{termcolor, Pretty};
use rustc_hir::{def_id::LocalDefId, HirId};
use rustc_index::IndexVec;
use rustc_middle::ty::{self as mir_ty, TyCtxt};

use crate::analyze::{self, did_cache::DefIdCache};
use crate::annot::AnnotFormula;
use crate::chc;
use crate::refine::{self, TypeBuilder};
use crate::rty;

#[derive(Debug, Clone)]
pub struct FormulaFn<'tcx> {
    params: IndexVec<rty::FunctionParamIdx, mir_ty::Ty<'tcx>>,
    formula: chc::Formula<rty::FunctionParamIdx>,
}

impl<'a, D> Pretty<'a, D, termcolor::ColorSpec> for &FormulaFn<'_>
where
    D: pretty::DocAllocator<'a, termcolor::ColorSpec>,
    D::Doc: Clone,
{
    fn pretty(self, allocator: &'a D) -> pretty::DocBuilder<'a, D, termcolor::ColorSpec> {
        allocator
            .intersperse(
                self.params.iter_enumerated().map(|(idx, ty)| {
                    idx.pretty(allocator)
                        .append(": ")
                        .append(allocator.as_string(ty))
                }),
                ", ",
            )
            .enclose("|", "|")
            .group()
            .append(self.formula.pretty(allocator))
            .group()
    }
}

impl<'tcx> FormulaFn<'tcx> {
    pub fn formula(&self) -> &chc::Formula<rty::FunctionParamIdx> {
        &self.formula
    }

    pub fn to_require_annot(&self) -> AnnotFormula<rty::FunctionParamIdx> {
        AnnotFormula::Formula(self.formula.clone())
    }

    /// Lowers an `ensures` formula function into a postcondition annotation.
    ///
    /// Relies on the layout produced by `thrust_macros::ensures`: parameter `0`
    /// is the function's return value (bound to [`rty::RefinedTypeVar::Value`])
    /// and parameters `1..n` are the enclosing function's parameters in order
    /// (mapped to [`rty::RefinedTypeVar::Free`]).
    pub fn to_ensure_annot(&self) -> AnnotFormula<rty::RefinedTypeVar<rty::FunctionParamIdx>> {
        AnnotFormula::Formula(self.formula.clone().map_var(|v| {
            if v.as_usize() == 0 {
                rty::RefinedTypeVar::Value
            } else {
                rty::RefinedTypeVar::Free(rty::FunctionParamIdx::from(v.as_usize() - 1))
            }
        }))
    }

    /// Lowers a refinement-type formula function (generated by the `param` /
    /// `ret` / `sig` macros) into a [`rty::Refinement`].
    ///
    /// Relies on the layout produced by those macros: parameter `0` is the
    /// refinement's value binder (mapped to [`rty::RefinedTypeVar::Value`])
    /// and the remaining parameters carry the formula's free variables,
    /// mapped to [`rty::RefinedTypeVar::Free`].
    pub fn to_refinement(&self) -> rty::Refinement<rty::FunctionParamIdx> {
        self.formula
            .clone()
            .map_var(|v| {
                if v.as_usize() == 0 {
                    rty::RefinedTypeVar::Value
                } else {
                    rty::RefinedTypeVar::Free(rty::FunctionParamIdx::from(v.as_usize() - 1))
                }
            })
            .into()
    }
}

#[derive(Debug, Clone, Copy)]
enum AmbiguousBinOp {
    Eq,
    Ne,
    Ge,
    Le,
    Gt,
    Lt,
}

#[derive(Debug, Clone)]
enum FormulaOrTerm<T> {
    Formula(chc::Formula<T>),
    Term(chc::Term<T>),
    BinOp(chc::Term<T>, AmbiguousBinOp, chc::Term<T>),
    And(Box<FormulaOrTerm<T>>, Box<FormulaOrTerm<T>>),
    Or(Box<FormulaOrTerm<T>>, Box<FormulaOrTerm<T>>),
    Implies(Box<FormulaOrTerm<T>>, Box<FormulaOrTerm<T>>),
    Not(Box<FormulaOrTerm<T>>),
    Literal(bool),
}

impl<T> FormulaOrTerm<T> {
    fn into_formula(self) -> Option<chc::Formula<T>> {
        let fo = match self {
            FormulaOrTerm::Formula(fo) => fo,
            FormulaOrTerm::Term { .. } => return None,
            FormulaOrTerm::BinOp(lhs, binop, rhs) => {
                let pred = match binop {
                    AmbiguousBinOp::Eq => chc::KnownPred::EQUAL,
                    AmbiguousBinOp::Ne => chc::KnownPred::NOT_EQUAL,
                    AmbiguousBinOp::Ge => chc::KnownPred::GREATER_THAN_OR_EQUAL,
                    AmbiguousBinOp::Le => chc::KnownPred::LESS_THAN_OR_EQUAL,
                    AmbiguousBinOp::Gt => chc::KnownPred::GREATER_THAN,
                    AmbiguousBinOp::Lt => chc::KnownPred::LESS_THAN,
                };
                chc::Formula::Atom(chc::Atom::new(pred.into(), vec![lhs, rhs]))
            }
            FormulaOrTerm::And(lhs, rhs) => lhs.into_formula()?.and(rhs.into_formula()?),
            FormulaOrTerm::Or(lhs, rhs) => lhs.into_formula()?.or(rhs.into_formula()?),
            FormulaOrTerm::Implies(lhs, rhs) => lhs.into_formula()?.implies(rhs.into_formula()?),
            FormulaOrTerm::Not(formula_or_term) => formula_or_term.into_formula()?.not(),
            FormulaOrTerm::Literal(b) => {
                if b {
                    chc::Formula::top()
                } else {
                    chc::Formula::bottom()
                }
            }
        };
        Some(fo)
    }

    fn into_term(self) -> Option<chc::Term<T>> {
        let t = match self {
            FormulaOrTerm::Formula { .. } => return None,
            FormulaOrTerm::Term(t) => t,
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Eq, rhs) => lhs.eq(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Ne, rhs) => lhs.ne(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Ge, rhs) => lhs.ge(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Le, rhs) => lhs.le(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Gt, rhs) => lhs.gt(rhs),
            FormulaOrTerm::BinOp(lhs, AmbiguousBinOp::Lt, rhs) => lhs.lt(rhs),
            FormulaOrTerm::And(lhs, rhs) => lhs.into_term()?.and(rhs.into_term()?),
            FormulaOrTerm::Or(lhs, rhs) => lhs.into_term()?.or(rhs.into_term()?),
            FormulaOrTerm::Implies(lhs, rhs) => lhs.into_term()?.not().or(rhs.into_term()?),
            FormulaOrTerm::Not(formula_or_term) => formula_or_term.into_term()?.not(),
            FormulaOrTerm::Literal(b) => chc::Term::bool(b),
        };
        Some(t)
    }
}

#[derive(Clone)]
pub struct AnnotFnTranslator<'a, 'tcx> {
    tcx: TyCtxt<'tcx>,
    local_def_id: LocalDefId,
    analyzer: &'a analyze::Analyzer<'tcx>,

    typeck: &'tcx mir_ty::TypeckResults<'tcx>,
    body: &'tcx rustc_hir::Body<'tcx>,
    generic_args: mir_ty::GenericArgsRef<'tcx>,

    def_ids: DefIdCache<'tcx>,
    type_builder: TypeBuilder<'tcx>,
    env: HashMap<HirId, chc::Term<rty::FunctionParamIdx>>,
}

impl<'a, 'tcx> AnnotFnTranslator<'a, 'tcx> {
    pub fn new(
        analyzer: &'a analyze::Analyzer<'tcx>,
        local_def_id: LocalDefId,
        generic_args: mir_ty::GenericArgsRef<'tcx>,
    ) -> Self {
        let tcx = analyzer.tcx();
        let body = tcx.hir_body_owned_by(local_def_id);
        let typeck = tcx.typeck(local_def_id);
        let def_ids = analyzer.def_ids();
        let type_builder = TypeBuilder::new(tcx, def_ids.clone(), local_def_id.to_def_id());
        let mut translator = Self {
            tcx,
            local_def_id,
            analyzer,
            typeck,
            body,
            generic_args,
            def_ids,
            type_builder,
            env: HashMap::default(),
        };
        translator.build_env_from_params();
        translator
    }

    pub fn with_def_id_cache(mut self, def_ids: DefIdCache<'tcx>) -> Self {
        self.def_ids = def_ids;
        self.type_builder = TypeBuilder::new(
            self.tcx,
            self.def_ids.clone(),
            self.local_def_id.to_def_id(),
        );
        self
    }

    fn build_env_from_params(&mut self) {
        for (idx, param) in self.body.params.iter().enumerate() {
            let param_idx = rty::FunctionParamIdx::from(idx);
            let mir_ty = self.pat_ty(param.pat);
            let ty = self.type_builder.build(mir_ty);
            let term = if !self.is_fn_param_wrapper_ty(mir_ty) && ty.to_sort().is_singleton() {
                // the analyzer don't expect params with singleton sorts to be used in formula...
                // FIXME: fix the analyzer side to uniformly accept all params
                Self::singleton_term_for_ty(&ty).unwrap()
            } else {
                chc::Term::var(param_idx)
            };
            self.build_env_from_pat(term, param.pat);
        }
    }

    fn singleton_term_for_ty(
        ty: &rty::Type<rty::Closed>,
    ) -> Option<chc::Term<rty::FunctionParamIdx>> {
        match ty {
            rty::Type::String | rty::Type::Never | rty::Type::Function(_) => {
                Some(chc::Term::null())
            }
            rty::Type::Tuple(ty) => ty
                .elems
                .iter()
                .map(|elem| Self::singleton_term_for_ty(&elem.ty))
                .collect::<Option<Vec<_>>>()
                .map(chc::Term::tuple),
            rty::Type::Pointer(ty) => {
                let elem = Self::singleton_term_for_ty(&ty.elem.ty)?;
                match ty.kind {
                    rty::PointerKind::Own | rty::PointerKind::Ref(rty::RefKind::Immut) => {
                        Some(chc::Term::box_(elem))
                    }
                    rty::PointerKind::Ref(rty::RefKind::Mut) => {
                        Some(chc::Term::mut_(elem.clone(), elem))
                    }
                }
            }
            rty::Type::Array(ty) => {
                if Self::singleton_term_for_ty(&ty.elem.ty).is_some() {
                    panic!("singleton array type is not supported in formula: {:?}", ty);
                }
                None
            }
            _ => None,
        }
    }

    fn is_fn_param_wrapper_ty(&self, ty: mir_ty::Ty<'tcx>) -> bool {
        ty.ty_adt_def()
            .is_some_and(|def| Some(def.did()) == self.def_ids.fn_param_wrapper())
    }

    fn build_env_from_pat(
        &mut self,
        param: chc::Term<rty::FunctionParamIdx>,
        pat: &'tcx rustc_hir::Pat<'tcx>,
    ) {
        use rustc_hir::PatKind;

        match pat.kind {
            PatKind::Binding(_, hir_id, _, None) => {
                self.env.insert(hir_id, param);
            }
            PatKind::TupleStruct(_, subpats, _) | PatKind::Tuple(subpats, _) => {
                for (idx, subpat) in subpats.iter().enumerate() {
                    let field_term = param.clone().tuple_proj(idx);
                    self.build_env_from_pat(field_term, subpat);
                }
            }
            _ => unimplemented!("unsupported pattern in formula: {:?}", pat),
        }
    }

    fn expr_ty(&self, expr: &'tcx rustc_hir::Expr<'tcx>) -> mir_ty::Ty<'tcx> {
        let ty = self.typeck.expr_ty(expr);
        let instantiated = mir_ty::EarlyBinder::bind(ty).instantiate(self.tcx, self.generic_args);
        let typing_env = mir_ty::TypingEnv::fully_monomorphized();
        self.tcx.normalize_erasing_regions(typing_env, instantiated)
    }

    fn pat_ty(&self, pat: &'tcx rustc_hir::Pat<'tcx>) -> mir_ty::Ty<'tcx> {
        let ty = self.typeck.pat_ty(pat);
        let instantiated = mir_ty::EarlyBinder::bind(ty).instantiate(self.tcx, self.generic_args);
        let typing_env = mir_ty::TypingEnv::fully_monomorphized();
        self.tcx.normalize_erasing_regions(typing_env, instantiated)
    }

    pub fn to_formula_fn(&self) -> FormulaFn<'tcx> {
        let formula = self.to_formula(self.body.value);
        let params = self
            .tcx
            .fn_sig(self.local_def_id.to_def_id())
            .instantiate(self.tcx, self.generic_args)
            .skip_binder()
            .inputs()
            .to_vec();
        FormulaFn {
            params: IndexVec::from_raw(params),
            formula,
        }
    }

    fn to_formula(&self, hir: &'tcx rustc_hir::Expr<'tcx>) -> chc::Formula<rty::FunctionParamIdx> {
        self.to_formula_or_term(hir)
            .into_formula()
            .expect("expected a formula")
    }

    fn to_term(&self, hir: &'tcx rustc_hir::Expr<'tcx>) -> chc::Term<rty::FunctionParamIdx> {
        self.to_formula_or_term(hir)
            .into_term()
            .expect("expected a term")
    }

    fn receiver_closure_ty(&self, ty: mir_ty::Ty<'tcx>) -> Option<mir_ty::Ty<'tcx>> {
        let inner = match ty.kind() {
            mir_ty::TyKind::Adt(adt, args) if Some(adt.did()) == self.def_ids.mut_model() => {
                args.type_at(0)
            }
            mir_ty::TyKind::Ref(_, inner_ty, mir_ty::Mutability::Not) => *inner_ty,
            _ => ty,
        };
        match inner.kind() {
            mir_ty::TyKind::Adt(adt, args) if Some(adt.did()) == self.def_ids.closure_model() => {
                Some(args.type_at(0))
            }
            _ => None,
        }
    }

    /// Resolves the [`rty::FunctionType`] of the closure contract referred to by the receiver.
    ///
    /// The receiver type is instantiated to the actual closure type in the formula function; its
    /// `DefId` is used to look up the contract collected by the analyzer.
    fn receiver_closure_fn_type(&self, receiver_ty: mir_ty::Ty<'tcx>) -> Option<rty::FunctionType> {
        let closure_ty = self.receiver_closure_ty(receiver_ty)?;
        let mir_ty::TyKind::Closure(def_id, args) = closure_ty.kind() else {
            return None;
        };
        self.analyzer
            .known_function_ty_with_args(*def_id, self.tcx.mk_args(args.as_closure().parent_args()))
    }

    /// Extracts the logical argument terms passed to `closure_precondition`/
    /// `closure_postcondition`. The arguments are supplied as a single tuple (e.g. `(x,)` or
    /// `()`), whose elements are the logical arguments of the closure.
    fn closure_spec_args(
        &self,
        arg: &'tcx rustc_hir::Expr<'tcx>,
    ) -> Vec<chc::Term<rty::FunctionParamIdx>> {
        match arg.kind {
            rustc_hir::ExprKind::Tup(elems) => elems.iter().map(|e| self.to_term(e)).collect(),
            _ => vec![self.to_term(arg)],
        }
    }

    /// The values of a closure's parameters: the closure's first (RustCall) parameter is its
    /// environment, which is the closure value itself, followed by the logical arguments.
    fn translate_closure_precondition(
        &self,
        receiver: &'tcx rustc_hir::Expr<'tcx>,
        args: &'tcx rustc_hir::Expr<'tcx>,
    ) -> FormulaOrTerm<rty::FunctionParamIdx> {
        let receiver_ty = self.expr_ty(receiver);
        let fn_ty = self
            .receiver_closure_fn_type(receiver_ty)
            .unwrap_or_else(|| {
                panic!(
                    "precondition used on a non-closure parameter: {:?}",
                    receiver
                )
            });
        let logical_args = self.closure_spec_args(args);
        // `fn_ty` is a closure (RustCall ABI), so its parameters are `[env, args..]`, where the
        // environment is the closure value itself.
        assert_eq!(
            logical_args.len(),
            fn_ty.params.len() - 1,
            "closure precondition arity mismatch: closure takes {} argument(s)",
            fn_ty.params.len() - 1
        );
        let param_args: Vec<_> = std::iter::once(self.to_term(receiver))
            .chain(logical_args)
            .collect();
        FormulaOrTerm::Formula(fn_ty.precondition_formula(&param_args))
    }

    fn translate_closure_postcondition(
        &self,
        receiver: &'tcx rustc_hir::Expr<'tcx>,
        args: &'tcx rustc_hir::Expr<'tcx>,
        result: &'tcx rustc_hir::Expr<'tcx>,
    ) -> FormulaOrTerm<rty::FunctionParamIdx> {
        let receiver_ty = self.expr_ty(receiver);
        let fn_ty = self
            .receiver_closure_fn_type(receiver_ty)
            .unwrap_or_else(|| {
                panic!(
                    "postcondition used on a non-closure parameter: {:?}",
                    receiver
                )
            });
        let logical_args = self.closure_spec_args(args);
        // `fn_ty` is a closure (RustCall ABI), so its parameters are `[env, args..]`, where the
        // environment is the closure value itself.
        assert_eq!(
            logical_args.len(),
            fn_ty.params.len() - 1,
            "closure postcondition arity mismatch: closure takes {} argument(s)",
            fn_ty.params.len() - 1
        );
        let param_args: Vec<_> = std::iter::once(self.to_term(receiver))
            .chain(logical_args)
            .collect();
        let result = self.to_term(result);
        FormulaOrTerm::Formula(fn_ty.postcondition_formula(&param_args, result))
    }

    fn arg_sort_at(&self, hir_id: HirId, idx: usize) -> chc::Sort {
        let generic_args = self.typeck.node_args(hir_id);
        let generic_args =
            mir_ty::EarlyBinder::bind(generic_args).instantiate(self.tcx, self.generic_args);
        self.type_builder.build(generic_args.type_at(idx)).to_sort()
    }

    /// Sort of the element type `T` for a `Seq<T>`-typed expression.
    fn seq_elem_sort_of(&self, expr: &'tcx rustc_hir::Expr<'tcx>) -> chc::Sort {
        let mir_ty::TyKind::Adt(_, args) = self.expr_ty(expr).kind() else {
            panic!("expected Seq-typed receiver");
        };
        self.type_builder.build(args.type_at(0)).to_sort()
    }

    fn variant_ctor_term(
        &self,
        ctor_did: rustc_span::def_id::DefId,
        result_ty: mir_ty::Ty<'tcx>,
        field_terms: Vec<chc::Term<rty::FunctionParamIdx>>,
    ) -> chc::Term<rty::FunctionParamIdx> {
        let variant_did = self.tcx.parent(ctor_did);
        let adt_did = self.tcx.parent(variant_did);
        let d_sym = crate::refine::datatype_symbol(self.tcx, adt_did);
        let variant_name = self.tcx.item_name(variant_did);
        let v_sym = chc::DatatypeSymbol::new(format!("{}.{}", d_sym, variant_name));
        let sort_args = if let mir_ty::TyKind::Adt(_, generic_args) = result_ty.kind() {
            generic_args
                .types()
                .map(|ty| self.type_builder.build(ty).to_sort())
                .collect()
        } else {
            panic!("expected an ADT type for variant constructor")
        };
        chc::Term::datatype_ctor(d_sym, sort_args, v_sym, field_terms)
    }

    fn to_formula_with_quantified_vars(
        &self,
        closure: &rustc_hir::Body<'tcx>,
    ) -> (
        Vec<(String, chc::Sort)>,
        chc::Formula<rty::FunctionParamIdx>,
    ) {
        let mut inner_translator = self.clone();
        let mut vars = Vec::new();
        for param in closure.params {
            let rustc_hir::PatKind::Binding(_, hir_id, ident, None) = param.pat.kind else {
                panic!(
                    "exists/forall closure parameter must be a simple binding: {:?}",
                    param.pat
                );
            };
            let param_ty = self.pat_ty(param.pat);
            let sort = self.type_builder.build(param_ty).to_sort();
            let var_term = chc::Term::FormulaQuantifiedVar(sort.clone(), ident.name.to_string());
            inner_translator.env.insert(hir_id, var_term);
            vars.push((ident.name.to_string(), sort));
        }
        let body_formula = inner_translator.to_formula(closure.value);
        (vars, body_formula)
    }

    fn to_formula_or_term(
        &self,
        hir: &'tcx rustc_hir::Expr<'tcx>,
    ) -> FormulaOrTerm<rty::FunctionParamIdx> {
        use rustc_hir::ExprKind;

        match hir.kind {
            ExprKind::Binary(op, lhs, rhs) => {
                match op.node {
                    rustc_hir::BinOpKind::Or => {
                        let lhs = self.to_formula_or_term(lhs);
                        let rhs = self.to_formula_or_term(rhs);
                        return FormulaOrTerm::Or(lhs.into(), rhs.into());
                    }
                    rustc_hir::BinOpKind::And => {
                        let lhs = self.to_formula_or_term(lhs);
                        let rhs = self.to_formula_or_term(rhs);
                        return FormulaOrTerm::And(lhs.into(), rhs.into());
                    }
                    rustc_hir::BinOpKind::Add => {
                        let lhs = self.to_term(lhs);
                        let rhs = self.to_term(rhs);
                        return FormulaOrTerm::Term(lhs.add(rhs));
                    }
                    rustc_hir::BinOpKind::Sub => {
                        let lhs = self.to_term(lhs);
                        let rhs = self.to_term(rhs);
                        return FormulaOrTerm::Term(lhs.sub(rhs));
                    }
                    rustc_hir::BinOpKind::Mul => {
                        let lhs = self.to_term(lhs);
                        let rhs = self.to_term(rhs);
                        return FormulaOrTerm::Term(lhs.mul(rhs));
                    }
                    _ => {}
                }

                let binop = match op.node {
                    rustc_hir::BinOpKind::Eq => AmbiguousBinOp::Eq,
                    rustc_hir::BinOpKind::Ne => AmbiguousBinOp::Ne,
                    rustc_hir::BinOpKind::Ge => AmbiguousBinOp::Ge,
                    rustc_hir::BinOpKind::Le => AmbiguousBinOp::Le,
                    rustc_hir::BinOpKind::Gt => AmbiguousBinOp::Gt,
                    rustc_hir::BinOpKind::Lt => AmbiguousBinOp::Lt,
                    _ => unimplemented!("unsupported binary operator in formula: {:?}", op),
                };
                let lhs = self.to_formula_or_term(lhs);
                let rhs = self.to_formula_or_term(rhs);
                FormulaOrTerm::BinOp(lhs.into_term().unwrap(), binop, rhs.into_term().unwrap())
            }
            ExprKind::Unary(op, operand) => match op {
                rustc_hir::UnOp::Neg => {
                    let operand = self.to_term(operand);
                    FormulaOrTerm::Term(operand.neg())
                }
                rustc_hir::UnOp::Not => {
                    let operand_ty = self.expr_ty(operand);
                    match operand_ty.ty_adt_def() {
                        Some(adt) if Some(adt.did()) == self.def_ids.mut_model() => {
                            let operand = self.to_term(operand);
                            FormulaOrTerm::Term(operand.mut_final())
                        }
                        _ => {
                            let operand = self.to_formula_or_term(operand);
                            FormulaOrTerm::Not(Box::new(operand))
                        }
                    }
                }
                rustc_hir::UnOp::Deref => {
                    let operand_ty = self.expr_ty(operand);
                    let term = self.to_term(operand);
                    if matches!(
                        operand_ty.kind(),
                        mir_ty::TyKind::Ref(_, _, mir_ty::Mutability::Not)
                    ) {
                        return FormulaOrTerm::Term(term.box_current());
                    }
                    let adt = operand_ty
                        .ty_adt_def()
                        .expect("deref operand must be a model type");
                    if Some(adt.did()) == self.def_ids.mut_model() {
                        FormulaOrTerm::Term(term.mut_current())
                    } else if Some(adt.did()) == self.def_ids.box_model() {
                        FormulaOrTerm::Term(term.box_current())
                    } else {
                        unimplemented!(
                            "unsupported deref operand type in formula: {:?}",
                            operand_ty
                        )
                    }
                }
            },
            ExprKind::AddrOf(rustc_hir::BorrowKind::Ref, rustc_hir::Mutability::Not, operand) => {
                let operand = self.to_term(operand);
                FormulaOrTerm::Term(operand.boxed())
            }
            ExprKind::Lit(lit) => match lit.node {
                rustc_ast::LitKind::Int(i, _) => {
                    let n = i64::try_from(i.get())
                        .expect("integer literal out of i64 range in formula");
                    FormulaOrTerm::Term(chc::Term::int(n))
                }
                rustc_ast::LitKind::Bool(b) => FormulaOrTerm::Literal(b),
                _ => unimplemented!("unsupported literal in formula: {:?}", lit),
            },
            ExprKind::Path(qpath) => match self.typeck.qpath_res(&qpath, hir.hir_id) {
                rustc_hir::def::Res::Local(hir_id) => FormulaOrTerm::Term(
                    self.env
                        .get(&hir_id)
                        .expect("unbound variable in formula")
                        .clone(),
                ),
                rustc_hir::def::Res::Def(
                    rustc_hir::def::DefKind::Ctor(rustc_hir::def::CtorOf::Variant, _),
                    ctor_did,
                ) => {
                    FormulaOrTerm::Term(self.variant_ctor_term(ctor_did, self.expr_ty(hir), vec![]))
                }
                _ => unimplemented!("unsupported path in formula: {:?}", qpath),
            },
            ExprKind::Tup(exprs) => {
                let terms = exprs.iter().map(|e| self.to_term(e)).collect();
                FormulaOrTerm::Term(chc::Term::tuple(terms))
            }
            ExprKind::Field(expr, field) => {
                // Tuples use numeric field names (`.0`); structs (represented as
                // tuples in the logic) use named fields resolved to their position.
                let index = match field.name.as_str().parse::<usize>() {
                    Ok(index) => index,
                    Err(_) => {
                        let adt = self
                            .expr_ty(expr)
                            .ty_adt_def()
                            .expect("named field access on a non-ADT type");
                        adt.non_enum_variant()
                            .fields
                            .iter()
                            .position(|f| f.name == field.name)
                            .expect("unknown named field in formula")
                    }
                };
                let term = self.to_term(expr);
                FormulaOrTerm::Term(term.tuple_proj(index))
            }
            ExprKind::Index(array, index, _) => {
                let array_ty = self.expr_ty(array);
                let array_term = self.to_term(array);
                let index_term = self.to_term(index);
                let is_seq = array_ty
                    .ty_adt_def()
                    .is_some_and(|adt| Some(adt.did()) == self.def_ids.seq_model());
                let array_inner = if is_seq {
                    array_term.tuple_proj(0)
                } else {
                    array_term
                };
                FormulaOrTerm::Term(array_inner.select(index_term))
            }
            ExprKind::MethodCall(method, receiver, args, _) => {
                if let Some(def_id) = self.typeck.type_dependent_def_id(hir.hir_id) {
                    if Some(def_id) == self.def_ids.array_model_store() {
                        assert_eq!(args.len(), 2, "array_store takes exactly 2 arguments");
                        let array_term = self.to_term(receiver);
                        let index_term = self.to_term(&args[0]);
                        let value_term = self.to_term(&args[1]);
                        return FormulaOrTerm::Term(array_term.store(index_term, value_term));
                    }
                    if Some(def_id) == self.def_ids.fn_param_at_entry() {
                        assert!(
                            args.is_empty(),
                            "FnParam::at_entry does not take any arguments"
                        );
                        let t = self.to_term(receiver);
                        return FormulaOrTerm::Term(t);
                    }
                    if Some(def_id) == self.def_ids.seq_len() {
                        assert!(args.is_empty(), "Seq::len does not take any arguments");
                        let t = self.to_term(receiver);
                        return FormulaOrTerm::Term(t.tuple_proj(1));
                    }
                    if Some(def_id) == self.def_ids.seq_push() {
                        assert_eq!(args.len(), 1, "Seq::push takes exactly 1 argument");
                        let t = self.to_term(receiver);
                        let v = self.to_term(&args[0]);
                        let arr = t.clone().tuple_proj(0);
                        let len = t.tuple_proj(1);
                        let new_arr = arr.store(len.clone(), v);
                        let new_len = len.add(chc::Term::int(1));
                        return FormulaOrTerm::Term(chc::Term::tuple(vec![new_arr, new_len]));
                    }
                    if Some(def_id) == self.def_ids.seq_concat() {
                        assert_eq!(args.len(), 1, "Seq::concat takes exactly 1 argument");
                        let elem_sort = self.seq_elem_sort_of(receiver);
                        self.analyzer.mark_uses_seq_concat(elem_sort.clone());
                        let t = self.to_term(receiver);
                        let other = self.to_term(&args[0]);
                        let a_arr = t.clone().tuple_proj(0);
                        let a_len = t.tuple_proj(1);
                        let b_arr = other.clone().tuple_proj(0);
                        let b_len = other.tuple_proj(1);
                        let new_arr = chc::Term::SeqConcatArr(
                            elem_sort,
                            vec![a_arr, a_len.clone(), b_arr, b_len.clone()],
                        );
                        let new_len = a_len.add(b_len);
                        return FormulaOrTerm::Term(chc::Term::tuple(vec![new_arr, new_len]));
                    }
                    if Some(def_id) == self.def_ids.seq_subsequence() {
                        assert_eq!(args.len(), 2, "Seq::subsequence takes exactly 2 arguments");
                        let elem_sort = self.seq_elem_sort_of(receiver);
                        self.analyzer.mark_uses_seq_subseq(elem_sort.clone());
                        let t = self.to_term(receiver);
                        let l = self.to_term(&args[0]);
                        let r = self.to_term(&args[1]);
                        let arr = t.tuple_proj(0);
                        let new_arr =
                            chc::Term::SeqSubseqArr(elem_sort, vec![arr, l.clone(), r.clone()]);
                        let new_len = r.sub(l);
                        return FormulaOrTerm::Term(chc::Term::tuple(vec![new_arr, new_len]));
                    }
                }
                unimplemented!("unsupported method call in formula: {:?}", method)
            }
            ExprKind::Call(func_expr, args) => {
                if let ExprKind::Path(qpath) = &func_expr.kind {
                    let res = self.typeck.qpath_res(qpath, func_expr.hir_id);
                    if let rustc_hir::def::Res::Def(def_kind, def_id) = res {
                        if Some(def_id) == self.def_ids.closure_precondition() {
                            let [receiver, args] = args else {
                                panic!(
                                    "closure_precondition takes a closure and a tuple of arguments"
                                );
                            };
                            return self.translate_closure_precondition(receiver, args);
                        }
                        if Some(def_id) == self.def_ids.closure_postcondition() {
                            let [receiver, args, result] = args else {
                                panic!(
                                    "closure_postcondition takes a closure, a tuple of arguments, and a result"
                                );
                            };
                            return self.translate_closure_postcondition(receiver, args, result);
                        }
                        if Some(def_id) == self.def_ids.exists() {
                            assert_eq!(args.len(), 1, "exists takes exactly 1 argument");
                            let ExprKind::Closure(closure) = args[0].kind else {
                                panic!("exists argument must be a closure");
                            };
                            let closure_body = self.tcx.hir_body(closure.body);

                            let (vars, body_formula) =
                                self.to_formula_with_quantified_vars(closure_body);
                            return FormulaOrTerm::Formula(chc::Formula::exists(
                                vars,
                                body_formula,
                            ));
                        }
                        if Some(def_id) == self.def_ids.forall() {
                            assert_eq!(args.len(), 1, "forall takes exactly 1 argument");
                            let ExprKind::Closure(closure) = args[0].kind else {
                                panic!("forall argument must be a closure");
                            };
                            let closure_body = self.tcx.hir_body(closure.body);

                            let (vars, body_formula) =
                                self.to_formula_with_quantified_vars(closure_body);
                            return FormulaOrTerm::Formula(chc::Formula::forall(
                                vars,
                                body_formula,
                            ));
                        }
                        if Some(def_id) == self.def_ids.fn_param_at_entry() {
                            assert_eq!(args.len(), 1, "FnParam::at_entry takes exactly 1 argument");
                            let t = self.to_term(&args[0]);
                            return FormulaOrTerm::Term(t);
                        }
                        if Some(def_id) == self.def_ids.implies() {
                            let [lhs, rhs] = args else {
                                panic!("implies takes exactly 2 arguments");
                            };
                            let lhs = self.to_formula_or_term(lhs);
                            let rhs = self.to_formula_or_term(rhs);
                            return FormulaOrTerm::Implies(lhs.into(), rhs.into());
                        }
                        if Some(def_id) == self.def_ids.mut_model_new() {
                            assert_eq!(args.len(), 2, "Mut::new takes exactly 2 arguments");
                            let t1 = self.to_term(&args[0]);
                            let t2 = self.to_term(&args[1]);
                            return FormulaOrTerm::Term(chc::Term::mut_(t1, t2));
                        }
                        if Some(def_id) == self.def_ids.box_model_new() {
                            assert_eq!(args.len(), 1, "Box::new takes exactly 1 argument");
                            let t = self.to_term(&args[0]);
                            return FormulaOrTerm::Term(chc::Term::box_(t));
                        }
                        if Some(def_id) == self.def_ids.seq_empty() {
                            assert!(args.is_empty(), "Seq::empty does not take any arguments");
                            let elem_sort = self.arg_sort_at(func_expr.hir_id, 0);
                            return FormulaOrTerm::Term(chc::Term::tuple(vec![
                                chc::Term::EmptyArray(elem_sort),
                                chc::Term::int(0),
                            ]));
                        }
                        if Some(def_id) == self.def_ids.seq_singleton() {
                            assert_eq!(args.len(), 1, "Seq::singleton takes exactly 1 argument");
                            let v = self.to_term(&args[0]);
                            let elem_sort = self.arg_sort_at(func_expr.hir_id, 0);
                            let new_arr =
                                chc::Term::EmptyArray(elem_sort).store(chc::Term::int(0), v);
                            return FormulaOrTerm::Term(chc::Term::tuple(vec![
                                new_arr,
                                chc::Term::int(1),
                            ]));
                        }
                        if let rustc_hir::def::DefKind::Ctor(ctor_of, _) = def_kind {
                            let terms = args.iter().map(|e| self.to_term(e)).collect();
                            match ctor_of {
                                rustc_hir::def::CtorOf::Variant => {
                                    return FormulaOrTerm::Term(self.variant_ctor_term(
                                        def_id,
                                        self.expr_ty(hir),
                                        terms,
                                    ));
                                }
                                rustc_hir::def::CtorOf::Struct => {
                                    return FormulaOrTerm::Term(chc::Term::tuple(terms));
                                }
                            }
                        }
                        if self
                            .tcx
                            .get_attrs_by_path(def_id, &analyze::annot::predicate_path())
                            .next()
                            .is_some()
                        {
                            let typing_env = mir_ty::TypingEnv::fully_monomorphized();
                            let generic_args = self.typeck.node_args(func_expr.hir_id);
                            tracing::debug!(
                                lhs = ?def_id,
                                lhs_generic_args = ?generic_args,
                                outer = ?self.local_def_id,
                                outer_generic_args = ?self.generic_args,
                                "resolving predicate call in formula"
                            );
                            let generic_args = mir_ty::EarlyBinder::bind(generic_args)
                                .instantiate(self.tcx, self.generic_args);
                            let instance = mir_ty::Instance::try_resolve(
                                self.tcx,
                                typing_env,
                                def_id,
                                generic_args,
                            )
                            .unwrap();
                            let pred_def_id = if let Some(instance) = instance {
                                instance.def_id()
                            } else {
                                def_id
                            };
                            let pred = refine::user_defined_pred(self.tcx, pred_def_id);
                            let arg_terms = args.iter().map(|e| self.to_term(e)).collect();
                            let atom = chc::Atom::new(pred.into(), arg_terms);
                            return FormulaOrTerm::Formula(chc::Formula::Atom(atom));
                        }
                    }
                }
                unimplemented!("unsupported call in formula: {:?}", func_expr)
            }
            ExprKind::Block(block, _) => {
                if block.stmts.is_empty() {
                    self.to_formula_or_term(block.expr.expect("expected an expression in block"))
                } else {
                    unimplemented!("unsupported block in formula: {:?}", block);
                }
            }
            _ => unimplemented!("unsupported expression in formula: {:?}", hir),
        }
    }
}
