name: Setup Z3
description: Sets up Z3 CLI in your GitHub Actions workflow.
inputs:
  z3-version:
    description: The version of Z3 to install.
    required: false
    default: 4.16.0
  z3-variant:
    description: The variant of Z3 to install (includes arch, e.g. x64-glibc-2.39, arm64-glibc-2.38).
    required: false
    default: x64-glibc-2.39
  z3-sha256sum:
    description: Expected sha256sum of downloaded binary archive.
    required: false
    default: |
      7288c49a5bd6dbafd7b0b0d1f65956b91672da24b08f09242919af159be3418e  z3-4.16.0-x64-glibc-2.39.zip
      87fcd963d3eecb0f12cf1c3ef0ad74e84a3a7bd3caed5d94445645ef94ae6274  z3-4.16.0-arm64-glibc-2.38.zip
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        wget -q "$RELEASE_URL/$RELEASE_NAME.zip"
        echo "$INPUT_Z3_SHA256SUM" | grep "$RELEASE_NAME.zip" | sha256sum --check --strict
        unzip "$RELEASE_NAME.zip"
        rm -f "$RELEASE_NAME.zip"
        mv "$RELEASE_NAME" ~/.setup-z3
        echo ~/.setup-z3/bin >> $GITHUB_PATH
      env:
        RELEASE_URL: https://github.com/Z3Prover/z3/releases/download/z3-${{ inputs.z3-version }}
        RELEASE_NAME: z3-${{ inputs.z3-version }}-${{ inputs.z3-variant }}
        INPUT_Z3_SHA256SUM: ${{ inputs.z3-sha256sum }}
