name: Setup Z3
description: Sets up Z3 CLI in your GitHub Actions workflow.
inputs:
  z3-version:
    description: The version of Z3 to install.
    required: false
    default: 4.15.4
  z3-variant:
    description: The variant of Z3 to install (includes arch, e.g. x64-glibc-2.39, arm64-glibc-2.34).
    required: false
    default: x64-glibc-2.39
  z3-sha256sum:
    description: Expected sha256sum of downloaded binary archive.
    required: false
    default: |
      a41b690e89c343931471506cdc6d957b6044a200fd2d240cc017432afdff7d3e  z3-4.15.4-x64-glibc-2.39.zip
      9e832578e28d9ed51a79b97948728a874854a3c38ee49e7aae05e7d6e0e93508  z3-4.15.4-arm64-glibc-2.34.zip
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        wget -q "$RELEASE_URL/$RELEASE_NAME.zip"
        echo "$INPUT_Z3_SHA256SUM" | grep "$RELEASE_NAME.zip" | sha256sum --check --strict
        unzip "$RELEASE_NAME.zip"
        rm -f "$RELEASE_NAME.zip"
        mv "$RELEASE_NAME" ~/.setup-z3
        echo ~/.setup-z3/bin >> $GITHUB_PATH
      env:
        RELEASE_URL: https://github.com/Z3Prover/z3/releases/download/z3-${{ inputs.z3-version }}
        RELEASE_NAME: z3-${{ inputs.z3-version }}-${{ inputs.z3-variant }}
        INPUT_Z3_SHA256SUM: ${{ inputs.z3-sha256sum }}
