name: Setup Z3
description: Sets up Z3 CLI in your GitHub Actions workflow.
inputs:
  z3-version:
    description: The version of Z3 to install.
    required: false
    default: 4.15.8
  z3-variant:
    description: The variant of Z3 to install (includes arch, e.g. x64-glibc-2.39, arm64-glibc-2.38).
    required: false
    default: x64-glibc-2.39
  z3-sha256sum:
    description: Expected sha256sum of downloaded binary archive.
    required: false
    default: |
      08a3312ef3a632c6e203c07ebdf19ef42f4975c1bd077e25501d204f674542fd  z3-4.15.8-x64-glibc-2.39.zip
      5d2e5e63018827b9611c15e1bfa48ffd9c0eaeeda6bdf184fd0963cbc0471528  z3-4.15.8-arm64-glibc-2.38.zip
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        wget -q "$RELEASE_URL/$RELEASE_NAME.zip"
        echo "$INPUT_Z3_SHA256SUM" | grep "$RELEASE_NAME.zip" | sha256sum --check --strict
        unzip "$RELEASE_NAME.zip"
        rm -f "$RELEASE_NAME.zip"
        mv "$RELEASE_NAME" ~/.setup-z3
        echo ~/.setup-z3/bin >> $GITHUB_PATH
      env:
        RELEASE_URL: https://github.com/Z3Prover/z3/releases/download/z3-${{ inputs.z3-version }}
        RELEASE_NAME: z3-${{ inputs.z3-version }}-${{ inputs.z3-variant }}
        INPUT_Z3_SHA256SUM: ${{ inputs.z3-sha256sum }}
