on:
  pull_request:
  push:

permissions: {}

jobs:
  fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-z3
      - name: Install PCSat dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            libblas3 \
            libgcc-s1 \
            libgmp10 \
            liblapack3 \
            libmpfr6 \
            libstdc++6 \
            zlib1g
      - name: Download latest PCSat
        run: |
          cd $(mktemp -d)
          curl -fsS "$PCSAT_URL" -o thrust-pcsat-wrapper.tar.gz
          echo "$PCSAT_SHA256 thrust-pcsat-wrapper.tar.gz" | sha256sum -c --strict
          tar --strip-components=1 -xf thrust-pcsat-wrapper.tar.gz
          mv thrust-pcsat-wrapper "$GITHUB_WORKSPACE/tests/thrust-pcsat-wrapper"
        env:
          PCSAT_URL: https://thrust-ci-public.s3.ap-northeast-1.amazonaws.com/pcsat/thrust-pcsat-wrapper-873d558c6a.tar.gz
          PCSAT_SHA256: cae6829b40cfde196ae231f4a97eed5b873756cb59619f580934b488c1e7a11a
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
