on:
  pull_request:
  push:

permissions: {}

jobs:
  fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-z3
      - run: curl -fsS "$PCSAT_URL" -o tests/thrust-pcsat-wrapper
        env:
          PCSAT_URL: https://thrust-ci-public.s3.ap-northeast-1.amazonaws.com/pcsat/thrust-pcsat-wrapper-873d558c6a
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
